### ISSUE TITLE
TraceView header expander not working correctly

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-ui#12]
When the header of the trace view is collapsed, it leaves a bunch of whitespace. The goal of the expander was to allow for more screen real estate for the main timeline view.

![image](https://cloud.githubusercontent.com/assets/3523016/25710682/f00c31b2-30ba-11e7-8951-4e3609eccf9c.png)

![image](https://cloud.githubusercontent.com/assets/3523016/25710692/fa406a4a-30ba-11e7-96b1-b49c70b771ae.png)

cc @saminzadeh

**Comment by saminzadeh** [comment]
I remember seeing this but wasn't able to consistently reproduce it. Any particular steps you took to get it into this state?

**Comment by yurishkuro** [comment]
I just noticed - the whitespace is not permanent, when you start scrolling the main timeline it actually goes back up. It's just that the expander does not adjust anything below it. When I collapse it and do a tiny scroll, the timeline makes a sharp jump to the top to consume the new whitespace.

![image](https://cloud.githubusercontent.com/assets/3523016/25712518/e15ca0b6-30bf-11e7-8ab9-7619e4849fb0.png)
