### ISSUE TITLE
Left panel "Find Traces" is not scrollable

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-ui#16]
When I zoom in browser I am not able to see the bottom of left panel "Find Traces" neither to scroll down. I'm only able to scroll down trace instances.

![jaeger-zoom-in-100per](https://cloud.githubusercontent.com/assets/5618424/25939472/483c95fc-3633-11e7-967e-47500e9110df.jpg)

This issue was reported here in Red Hat MSA project when Jaeger is embedded in an iframe:
![msa-zoom-in-find-traces-not-scrollable](https://cloud.githubusercontent.com/assets/5618424/25939616/be5f616a-3633-11e7-93d1-620502e3fbc0.jpg)

**Comment by rafabene** [comment]
It also happens to me in a Mac with a resolution of 1280 x 800.

**Comment by saminzadeh** [comment]
Gathering some feedback on this, should we make each side scrollable or just have the whole page scroll without having the "Find Traces" section fixed?

**Comment by pavolloffay** [comment]
I would vote for 
>"Find Traces" section fixed

**Comment by rafabene** [comment]
I think that having both sides scrollable won't help if the user is not familiar with the UI. He won't understand that he has to scroll the right side to see a button that he has know idea that it exists.

My four cents (not in order of priority):
- Change the filter to be horizontal instead of vertical
- Change the button to the top (It might not be the best UX)
- Trigger the find button on the combo change selection event - This would allow people not familiar to the screen to see something happening even if not clicking/finding the button.
- Scroll both sides :)

**Comment by yurishkuro** [comment]
I don't like making the panel horizontal - it's what Zipkin does and it looks awful.

I prefer making the search params panel scrollable. To improve its usability
  * make the Search button (and add Reset button) to be fixed at the bottom (not scrollable)
  * add some visual indicator that panel can be scroller when it doesn't have enough vertical space

**Comment by objectiser** [comment]
Another option might be to place some of the components within collapsible regions - for example the lookback, min/max durations could be collapsed in a region entitled "Time Range". This would reduce the initial height so overcome the original problem.

**Comment by tiffon** [comment]
The original issue of the search form not scrolling was resolved in #53 with the removal of `react-sticky`. It's now scrollable as a regular page element.

![screen shot 2017-09-24 at 1 16 20 am](https://user-images.githubusercontent.com/2304337/30779714-08320d36-a0c6-11e7-9ec6-3de8aecd7c67.png)


The other UX directions discussed in this ticket have not been implemented.

@yurishkuro Is there a consensus on where the other UX changes have landed?

**Comment by yurishkuro** [comment]
> It's now scrollable as a regular page element.

it's not ideal but at least makes the form usable with zoom-in. I suggest closing this; #20 will take care of it in the long term.

**Comment by tiffon** [comment]
Fixed by #53.
