### ISSUE TITLE
got error when querying

### ISSUE THREAD

**Issue by ggaaooppeenngg** [uber/jaeger-ui#28]
I deploy individual component manually, and got `There was an error querying for traces:
Unexpected token < in JSON at position 0` on the ui, like this.
![image](https://cloud.githubusercontent.com/assets/4769989/26398706/de7d0da2-40ac-11e7-8e46-ef91f8a00107.png)

It seems a query got a html response, so it can not be decoded by json decoder.

**Comment by saminzadeh** [comment]
Do you have the HTTP request details?

**Comment by ggaaooppeenngg** [comment]
![image](https://cloud.githubusercontent.com/assets/4769989/26437361/49718da2-414f-11e7-8e7e-84d2f8597394.png)

**Comment by ggaaooppeenngg** [comment]
I run `cqlsh:jaeger_v1_test> select * from traces;`, there are rows , so I guess there are problems with query or ui, there is there any raw query request I can use to test if query works?

**Comment by ggaaooppeenngg** [comment]
I run `http://localhost:16686/api/traces?service=my_service_name`, got desired results.

**Comment by ggaaooppeenngg** [comment]
I guess I missed `ssh -fN -L 3001:localhost:$JAEGER_BACKEND_PORT $JAEGER_BACKEND_HOST` locally on my machine, but I don't have ssh access to `$JAEGER_BACKEND_PORT`, can `localhost:3001` be specified to remote host port?

**Comment by saminzadeh** [comment]
Yes, as long as you can access the remote host. Going to close this since its not directly tied to jaeger-ui development.
