### ISSUE TITLE
Update to React 15.5

### ISSUE THREAD

**Issue by saminzadeh** [uber/jaeger-ui#3]
The latest version of React has been released: 
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by yurishkuro** [comment]
what would that bring us?

**Comment by saminzadeh** [comment]
No noticeable user changes but React 16 has some big breaking changes (propTypes, and deprecation of createClass) that we need to be up to to date with. 

We should upgrade and make sure we have no deprecation warnings
