### ISSUE TITLE
Provide a search interface for log events

### ISSUE THREAD

**Issue by homme** [uber/jaeger-ui#37]
I'm using the OpenTracing API to add baggage to spans, which has produced a trace with the following log:
![image](https://user-images.githubusercontent.com/1055336/27657237-e53f6894-5c43-11e7-88d5-d30d2e0dd194.png)
It would be great to be able to search traces for these events in a similar way to how tags can be searched e.g. something like the following to allow the example trace to be retrieved: `event:baggage key:req-id value:b5a0akvpjll153h06o1g`.

**Comment by black-adder** [comment]
The UI should already be able to query by logs, if not then there appears to be a bug in the backend.

**Comment by homme** [comment]
Great! I've had a look but can't find any documentation for how to format a log query: does it exist and if not could you provide an example?

**Comment by black-adder** [comment]
you query them the say way as you would tags `event:baggage|key:req-id|value:b5a0akvpjll153h06o1g`

**Comment by homme** [comment]
Thanks for the suggestion, but that doesn't return any traces for me (using the `jaegertracing/all-in-one:latest`  (051bae96e754) Docker image)
![image](https://user-images.githubusercontent.com/1055336/27659698-64611962-5c4c-11e7-950b-9c1b6429b0e1.png)

**Comment by vprithvi** [comment]
>you query them the same way as you would tags event:baggage|key:req-id|value:b5a0akvpjll153h06o1g

I've never had multiple tag search work for me either. I suspect it is because of the client side Cassandra joins. 

Further, the tag search only applies to spans from the selected service, and not tags in the entire trace. So searching for logs becomes very frustrating.

**Comment by homme** [comment]
> Further, the tag search only applies to spans from the selected service, and not tags in the entire trace.

@vprithvi thanks for your input - the above hint helped: the multi tag search now works when I select the appropriate root service!
