### ISSUE TITLE
Highlight error spans 

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-ui#4]
Hi,

does UI support highlighting error spans?

![error-span](https://cloud.githubusercontent.com/assets/5618424/25186758/647274e4-2521-11e7-9657-e841cf1b21d4.png)

**Comment by objectiser** [comment]
@pavolloffay Yes it does - see the image in our blog post: http://www.hawkular.org/blog/2017/04/19/hawkular-apm-jaeger.html

The selected span at the bottom showing the properties has 'error=true' and the line has a pink/red background.

**Comment by pavolloffay** [comment]
See attached picture, there is probably something wrong. 

Code looks good https://github.com/uber/jaeger-ui/search?utf8=%E2%9C%93&q=isErrorSpan&type=

**Comment by saminzadeh** [comment]
I'm wondering if the API is returning the error = "true" value has a string and is missing the equality check. 

Can you attach the JSON payload of the trace?

**Comment by objectiser** [comment]
Is it sensitive to the type of the tag? Is the tag value being stored as a boolean - although possibly it shouldn't matter (just in case).

**Comment by pavolloffay** [comment]
@objectiser indeed it is type sensitive see attached code above. 

JSON from web UI: https://pastebin.com/KfV5R9Y6 so it is `string`. jaeger client is java  0.18.0

**Comment by pavolloffay** [comment]
Probably mapping from zipkin thrift to internal model is buggy. I have also noticed that OT component tag is filtered out when using zipkin thrift.

cc @yurishkuro

What do we do with this? 
* keep as it is, current impl respects OT spec
* try to be more friendly and highlight on `error` with "true" as a string,
* or even highlight every span with error tag except error:false.

**Comment by yurishkuro** [comment]
we should fix the UI to respect `"true"` as a string

> or even highlight every span with error tag except error:false

mmm, I wouldn't do it just yet.

**Comment by yurishkuro** [comment]
or maybe better, we can add an adjuster on the server side, and fix strings to bools on ingestion or on serving to UI

**Comment by pavolloffay** [comment]
Could we get this fixed by simply testing on a string "true"?

**Comment by yurishkuro** [comment]
@pavolloffay yes, but that will only address the UI issue, any future data analysis code would need to keep checking for two values. I think it's best to sanitize the data on the server. Having said that, I am not against the UI fix.

**Comment by yurishkuro** [comment]
```js
src/components/TracePage/TraceTimelineViewer/utils.js:107:export const isErrorSpan = span => hasTagKey(span.tags, 'error', true);
```

easy to fix, but need a unit test

**Comment by pavolloffay** [comment]
+1 I just wanted to confirm that we agree before opening PR. I will do it tomorrow.
