### ISSUE TITLE
Find Traces Matching Multiple Services

### ISSUE THREAD

**Issue by frankgreco** [uber/jaeger-ui#41]
Currently, you can only search spans belonging to a one service. It would be nice if you could find traces belonging to multiple services. Then, you could search tags where `error:true` on all tags or search for traces which include multiple services.

**Comment by yurishkuro** [comment]
this might be possible with the upcoming Elasticsearch backend, but with Cassandra storage it would require extra writes to maintain an index without service name.

**Comment by tiffon** [comment]
@yurishkuro Should this ticket be moved to the query service as the backend work needs to precede any UI work on this?

**Comment by yurishkuro** [comment]
yes

**Comment by frankgreco** [comment]
I can move it

**Comment by frankgreco** [comment]
closing in favor of [https://github.com/jaegertracing/jaeger/issues/423](https://github.com/jaegertracing/jaeger/issues/423)
