### ISSUE TITLE
Filter by Tag Value Objects 

### ISSUE THREAD

**Issue by frankgreco** [uber/jaeger-ui#45]
Currently you can filter results by tag. It would be nice if the value of the tag was a JSON object to be able to further index the object. For example:

tag key: `http.headers`
tag value: `{"host": "foo.bar.com"}`

It would be great to filter on `http.headers.host:foo.bar.com`

**Comment by yurishkuro** [comment]
Are you suggesting an in-browser search on retrieved search results and/or a single trace?

If it's a suggestion for the backend search then please rebook in the main repo https://github.com/uber/jaeger/issues/

**Comment by frankgreco** [comment]
@yurishkuro I guess this would depend on where the logic is to currently filter results. When you receive results from the backend, do you only receive the results back that were searched for or do you narrow it down in the front end code?

**Comment by yurishkuro** [comment]
the UI has some dynamic filtering, but it's only on the Trace View atm, not on the main search page. The current tag query you can enter on the search page is executed on the backend.

**Comment by frankgreco** [comment]
in that case, the change would be on the backend. per your comment above, i'll close and reopen on the main repo.
