### ISSUE TITLE
Highlight error traces

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-ui#5]
UI currently highlights error spans, however users have to open trace instance view to see if an error happened, therefore UI could also highlight error traces (under `/search`). 

Possible views: 
* change color of entire trace 
* add number of error spans next to number of total spans per service.

**Comment by objectiser** [comment]
Second option sounds good to me - and possibly allow a filter criteria to return just error traces?

If the number of errors is > 0, then the number could still be highlighted in red to make it stand out.

**Comment by yurishkuro** [comment]
The color highlighting is a bit suboptimal way to visualize errors, imo, I booked #6 about that.

I like the idea of just showing the error counter

![image](https://cloud.githubusercontent.com/assets/3523016/25236698/78590e10-25b6-11e7-80c6-671f90082959.png)

**Comment by pavolloffay** [comment]
This looks fine and clear. I also like the idea when passport would show `passport(4, 2)`

**Comment by yurishkuro** [comment]
hm, `passport(4, 2)` seems a bit cryptic. Then `passport(4)` also becomes more cryptic when we add the error count.

**Comment by pavolloffay** [comment]
I mean `passport(2, 2)` with the last 2 being in red color. But agree there might be a better way maybe show red `!` next to `passport(4) !`. 

Proposed picture look fine to me. These UI things usually needs more iterations.

**Comment by tiffon** [comment]
Created [PR-17](https://github.com/uber/jaeger-ui/pull/17) to implement this.

**Comment by pavolloffay** [comment]
Thanks it looks good!
