### ISSUE TITLE
Span duration is offset from the span row

### ISSUE THREAD

**Issue by vprithvi** [uber/jaeger-ui#54]
In the single trace view, the duration isn't rendered at the center of the span.

This offset is particularly noticeable for error rows that are highlighted in pink.
![image](https://user-images.githubusercontent.com/833009/29218106-b89dc7a8-7e81-11e7-9d4e-d6edd7031a39.png)

This is on Safari Version 10.1 (12603.1.30.0.34)

To reproduce, run the latest hotROD demo using instructions at jaeger.readthedocs.io/en/latest/getting_started/

**Comment by tiffon** [comment]
@vprithvi I downloaded and ran the latest image and I'm not able to reproduce the issue.

This looks like an old image as the entire row is no longer highlighted when a span has an error tag.

Can you confirm this is running jaeger all in one image `73359e56febc` created on 8/10?

**Comment by vprithvi** [comment]
Thanks for taking a look.
It turned out that I hadn't docker pulled. Latest looks fine. Closing this issue.
