### ISSUE TITLE
No service dependencies found.

### ISSUE THREAD

**Issue by edukondalugorla** [uber/jaeger-ui#56]
Hi, i am new to jaeger ui. Jaeger ui showing like "No service dependencies found.". In package json i set proxy value to my  api server url  "http://localhost:16686". Please help me How to configure.

**Comment by pavolloffay** [comment]
hu @edukondalugorla what storage are you using? Because It's not currently supported with Cassandra.

**Comment by edukondalugorla** [comment]
I am not using any storage server, I am running a simple node js api server as like below code
=============
var express = require('express')  
var app = express()

app.get('/*', function (req, res) {  
  res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ a: 1 }, null, 3));
})

app.listen(16686, function () {  
  console.log('Example app listening on port 16686!')
});
===================

In package json porxy value configured to this server url  "localhost:16686". and i started Jaeger UI.

**Comment by saminzadeh** [comment]
The front end won't work without an instance of the Jaeger query service,. The `proxy` property in the `package.json` should point to that. You can run the jaeger query service via docker and have the front end point to that locally. Check out the [Getting Started](http://jaeger.readthedocs.io/en/latest/getting_started/)

**Comment by edukondalugorla** [comment]
Is there any sample demo app source code  for Jaeger query service without using docker.

**Comment by objectiser** [comment]
In the docs it explains how to run the individual backend components from source: http://jaeger.readthedocs.io/en/latest/getting_started/#running-individual-jaeger-components

**Comment by tiffon** [comment]
@edukondalugorla How is this going? Do you have any further questions?
