### ISSUE TITLE
Tag Value Span Does Not Scroll Horizontally

### ISSUE THREAD

**Issue by frankgreco** [uber/jaeger-ui#58]
**Description**

Tag value text does not horizontally scroll

**Steps to reproduce the issue:**
report a span with a really log tag value

**Describe the results you received:**
expected span to scroll horizontally

**Describe the results you expected:**
expected span to scroll horizontally

**Additional information you deem important (e.g. issue happens only occasionally):**
<img width="981" alt="screen shot 2017-08-18 at 10 08 33 am" src="https://user-images.githubusercontent.com/22604233/29465133-c89ded1e-83fd-11e7-8be3-a8ca88d4b391.png">

**Additional environment details (Browser, etc.):**
chrome

**Comment by frankgreco** [comment]
I believe this is the relevant code

```js
        {!open &&
          <span>
            {data.map(row =>
              <span className="px1">
                <span style={{ color: 'gray' }}>
                  {row.key}=
                </span>
                {row.value.toString()}
              </span>
            )}
          </span>}
```

**Comment by tiffon** [comment]
@frankgreco Thanks for reporting this. There is an [open PR](https://github.com/uber/jaeger-ui/pull/53) which should take care of it.

**Comment by ringerc** [comment]
Confirmed fixed by latest UI release
