### ISSUE TITLE
Hierarchical error span highlighting

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-ui#6]
Something we discussed in the past.
  1. Use a red icon (like a stop sigh) next to span name to indicate errors, instead of highlighting the whole row
  1. When the spans are collapsed, the error indicator should bubble up to the first visible ancestor span, but go back to the proper level when spans are expanded again.

**Comment by tiffon** [comment]
Created [PR-18](https://github.com/uber/jaeger-ui/pull/18) to implement this.

**Comment by yurishkuro** [comment]
Tip: if you add `Fixes #6` in the PR comment, it will auto-link here, and will close the issue once merged.

**Comment by tiffon** [comment]
I see. I thought it only applied to the commit message, and I didn't learn about that until after I had pushed to origin. Thanks for the tip!
