### ISSUE TITLE
Use canvas instead of SVG for trace mini-map

### ISSUE THREAD

**Issue by tiffon** [uber/jaeger-ui#61]
To improve performance on traces with many spans, use the [canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to render the trace mini-map instead of SVG elements.

**Comment by NeoCN** [comment]
@tiffon I got this render result after merge this
<img width="1896" alt="jietu20170919-101712" src="https://user-images.githubusercontent.com/1180502/30573053-2fb827e0-9cb7-11e7-972d-f71dda714ede.png">

**Comment by tiffon** [comment]
@NeoCN Thanks for reporting this. I'll work on this under a separate
ticket. Will keep you posted.



On Sep 18, 2017 10:36 PM, "NeoCN" <notifications@github.com> wrote:

@tiffon <https://github.com/tiffon> I got this render result after merge
this
[image: jietu20170919-101712]
<https://user-images.githubusercontent.com/1180502/30573053-2fb827e0-9cb7-11e7-972d-f71dda714ede.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uber/jaeger-ui/issues/61#issuecomment-330411067>, or mute
the thread

**Comment by tiffon** [comment]
@NeoCN I created #76 to track this. Thanks for reporting!
