### ISSUE TITLE
Make left column scrollable in trace detail view

### ISSUE THREAD

**Issue by tiffon** [uber/jaeger-ui#62]
Currently, if the viewport is small or when process / operation names are long, the left column truncates labels (see attached screenshot). 

Making the left column scrollable will accommodate deeply nested spans, long process or operation names, and small viewport sizes.

![span-name-truncation-marked](https://user-images.githubusercontent.com/2304337/29518474-7a75d574-8647-11e7-9f21-2abbbbbdddfa.png)

**Comment by tiffon** [comment]
I vote we kill this ticket. With the width of the left column being adjustable and the full text showing on mouseover, I agree with @jcorbin, this ticket is unnecessary. 

@jcorbin @yurishkuro Care to weigh in?

**Comment by yurishkuro** [comment]
sgtm

**Comment by tiffon** [comment]
Closing this as won't fix.
