### ISSUE TITLE
Sort operations for a service in TraceSearchForm

### ISSUE THREAD

**Issue by metalmatze** [uber/jaeger-ui#79]
**Description**
The TraceSearchForm currently shows all Operations as an unsorted list.
It would be really helpful if that list was sorted by name (ascending?)

I believe that this line has to have an additionally sort of the elements being passed?!
[TraceSearchForm.js#L106](https://github.com/uber/jaeger-ui/blob/master/src/components/SearchTracePage/TraceSearchForm.js#L106)

**Steps to reproduce the issue:**

1. Open the UI.
2. Pick a service.
3. Try finding a operation.

**Describe the results you received:**

![screenshot from 2017-09-21 17-24-08](https://user-images.githubusercontent.com/872251/30704219-58a5f0be-9ef2-11e7-95ff-05efc73875e2.png)

**Describe the results you expected:**

I expect the dropdown to be ordered by name in an ascending order to more easily find the operation I'm looking for.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (Browser, etc.):**

Chrome, but probably every browser.

**Comment by yurishkuro** [comment]
+1

I checked one of our services that has the most endpoints, they all came up sorted, but maybe it's a side effect of the storage backend returning them in that order.
