### ISSUE TITLE
Logs show 'event' as the first entry

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-ui#8]
Hi,

I think this would define a consistent way how to read logs as event is usually always present.

**Comment by yurishkuro** [comment]
What are you proposing?

The API Handler has an adjuster that sorts the log fields to put event in the first position. There are some todo's there because I think it should also move ahead things like `msg` and `level` if present.

**Comment by pavolloffay** [comment]
I'm proposing to show event in the first position as it is usually the most important log entry. 

It's better that it is handled in API handler. Is it already in place? What I see is this: 

![microservices frontend](https://cloud.githubusercontent.com/assets/5618424/25303108/76803554-274c-11e7-828e-98dacdc3884a.jpg)

**Comment by yurishkuro** [comment]
It's odd, event should already be pulled to the first position, see https://github.com/uber/jaeger/blob/master/cmd/query/app/adjusters.go#L33

**Comment by pavolloffay** [comment]
btw. I'm running it with latest all-in-one image.

**Comment by yurishkuro** [comment]
I found the issue, copy&paste of old code

**Comment by pavolloffay** [comment]
@yurishkuro++ thanks!
