### ISSUE TITLE
Span timeline not compatible with Safari

### ISSUE THREAD

**Issue by xiaogaozi** [uber/jaeger-ui#9]
<img width="1266" alt="screen shot 2017-04-26 at 16 40 46" src="https://cloud.githubusercontent.com/assets/149645/25425790/ab4cc3fa-2a9f-11e7-9d70-94863d51610e.png">

_Safari_

<img width="1273" alt="screen shot 2017-04-26 at 16 42 57" src="https://cloud.githubusercontent.com/assets/149645/25425791/abccae94-2a9f-11e7-8fd5-766272016790.png">

_Chrome_

**Comment by tiffon** [comment]
Created [PR-15](https://github.com/uber/jaeger-ui/pull/15) for this.

**Comment by saminzadeh** [comment]
Fixed with #15.
